[project]
name = "hw3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "joblib>=1.4.2",
    "loguru>=0.7.3",
    "notebook>=7.3.1",
    "numpy>=2.0.2",
    "opencv-python>=4.10.0.84",
    "salesforce-lavis>=1.0.2",
]
